url: "https://2024.reddotrubyconf.com"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Red Dot Ruby Conference 2024" # the name of your site, e.g. ACME Corp.

permalink: /:title/

collections:
  pages:
    output: true
    permalink: /:path/

timezone: Asia/Singapore

# Make live reloading of css work by rebuilding the css everytime there's a change
postcss:
  cache: false

exclude:
  - README.md
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

postcss:
  script: node_modules/.bin/postcss
  config: postcss.config.js

defaults:
  - scope:
      path: _pages/
    values:
      layout: default
  - scope:
      path: _posts/
    values:
      layout: post